### ISSUE TITLE
Update README to document new config format

### ISSUE THREAD

**Issue by jckuester** [jckuester/weather-station#21]
```
# test / sample configuration
sensors:
  1235:
    location: kitchen
    protocol: weather15
  91:
    location: fridge
    protocol: weather12
```
